package com.zhangli.myapplication;

public class DATAS {
    public static final int[] ICNS={
            R.drawable.img3,
            R.drawable.img4,
            R.drawable.img5,
            R.drawable.img6,
            R.drawable.img7,
            R.drawable.img8,
            R.drawable.img9,
            R.drawable.img10,
            R.drawable.img11,
            R.drawable.img12,
            R.drawable.img13,
            R.drawable.img14,
            R.drawable.img15,
            R.drawable.img16,
            R.drawable.img17,
            R.drawable.img18,
            R.drawable.img19,
            R.drawable.img20
    };
    public static  final int[] MEINVS={
            R.drawable.meinv1,
            R.drawable.img3,
            R.drawable.img4,
            R.drawable.meinv2,
            R.drawable.meinv3,
            R.drawable.meinv4,
            R.drawable.meinv5,
            R.drawable.meinv6,
            R.drawable.meinv7,
            R.drawable.img5,
            R.drawable.img6,
            R.drawable.img7,
            R.drawable.meinv8,
            R.drawable.meinv9,
            R.drawable.meinv10,
            R.drawable.meinv11,
            R.drawable.meinv12,
            R.drawable.meinv13,
            R.drawable.img16,
            R.drawable.img17,
            R.drawable.meinv14,
            R.drawable.meinv15,
            R.drawable.meinv16,
            R.drawable.meinv17,
            R.drawable.meinv18,
            R.drawable.meinv19,
            R.drawable.meinv20,
            R.drawable.meinv21,
            R.drawable.meinv22,
            R.drawable.meinv23,
    };
}
